name: "Download Binaries From Server"
description: "Download Binaries from Server"
author: "jhersonharyson"

inputs:
  host:
    description: "Host"
    required: true
    default: ${{github.event.repository.name}}
runs:
  using: "composite"
  steps:
    - name: Donwloading
      run: ${{ github.action_path }}/download.sh ${{inputs.host}}
      shell: bash
